<a href="https://colab.research.google.com/github/N-avi-N/Python_Basics/blob/main/Numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a = np.array([[1,2], [3,4], [5,6]])

In [5]:
print(a,'\n')
print(a.shape)

[[1 2]
 [3 4]
 [5 6]] 

(3, 2)


In [6]:
b = np.ones((3,4))
print(b,'\n')
print(b.shape)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] 

(3, 4)


In [7]:
c = np.eye(5)
print(c,'\n')
print(c.shape)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]] 

(5, 5)


Reshaping matrix

In [10]:
a = np.arange(8)
b = a.reshape((4,2))
c = a.reshape((2,2,-1))
d = c.flatten()
e = np.expand_dims(a,0)
f = np.expand_dims(a,1)
g = e.squeeze()

print(a)
print('-'*20)

print(b)
print('-'*20)

print(c)
print('-'*20)

print(d)
print('-'*20)

print(e)
print('-'*20)

print(f)
print('-'*20)

print(g)


[0 1 2 3 4 5 6 7]
--------------------
[[0 1]
 [2 3]
 [4 5]
 [6 7]]
--------------------
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
--------------------
[0 1 2 3 4 5 6 7]
--------------------
[[0 1 2 3 4 5 6 7]]
--------------------
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]
--------------------
[0 1 2 3 4 5 6 7]


In [13]:
a = np.ones((4,3))
b = np.ones((4,3))
c = np.concatenate([a,b], 0)

print(c,'\n')
print(c.shape)

d = np.concatenate([a,b], 1)
print(d,'\n')
print(d.shape)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] 

(8, 3)
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]] 

(4, 6)


In [14]:
# one application is to create a batch for NN
x1 = np.ones((32,32,3))
x2 = np.ones((32,32,3))
x3 = np.ones((32,32,3))
# --> to create a batch of shape (3,32,32,3)
x = [x1, x2, x3]
x = [np.expand_dims(xx, 0) for xx in x] # xx shape becomes (1,32,32,3)
x = np.concatenate(x, 0)
print(x.shape)

(3, 32, 32, 3)


In [16]:
a = np.zeros([10, 10])
a[:3] = 1
# a[:, :3] = 2
# a[:3, :3] = 3
# rows = [4,6,7]
# cols = [9,3,5]
# a[rows, cols] = 4
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [18]:
a = np.zeros([10, 10])
a[:, :3] = 2
print(a)

[[2. 2. 2. 0. 0. 0. 0. 0. 0. 0.]
 [2. 2. 2. 0. 0. 0. 0. 0. 0. 0.]
 [2. 2. 2. 0. 0. 0. 0. 0. 0. 0.]
 [2. 2. 2. 0. 0. 0. 0. 0. 0. 0.]
 [2. 2. 2. 0. 0. 0. 0. 0. 0. 0.]
 [2. 2. 2. 0. 0. 0. 0. 0. 0. 0.]
 [2. 2. 2. 0. 0. 0. 0. 0. 0. 0.]
 [2. 2. 2. 0. 0. 0. 0. 0. 0. 0.]
 [2. 2. 2. 0. 0. 0. 0. 0. 0. 0.]
 [2. 2. 2. 0. 0. 0. 0. 0. 0. 0.]]


In [19]:
a = np.zeros([10, 10])
a[:3, :3] = 3
print(a)

[[3. 3. 3. 0. 0. 0. 0. 0. 0. 0.]
 [3. 3. 3. 0. 0. 0. 0. 0. 0. 0.]
 [3. 3. 3. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [21]:
a = np.zeros([10, 10])
rows = [4,6,7]
cols = [9,3,5]
a[rows, cols] = 4
print(a)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 4.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 4. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 4. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


Transposition

In [24]:
# transposition
a = np.arange(24).reshape(2,3,4)
print(a.shape)
print(a,'\n')
print('-'*30)

a = np.transpose(a, (2,1,0)) # swap 0th and 2nd axes
print(a.shape)
print(a)

(2, 3, 4)
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]] 

------------------------------
(4, 3, 2)
[[[ 0 12]
  [ 4 16]
  [ 8 20]]

 [[ 1 13]
  [ 5 17]
  [ 9 21]]

 [[ 2 14]
  [ 6 18]
  [10 22]]

 [[ 3 15]
  [ 7 19]
  [11 23]]]


In [26]:
c = np.array([[1,2],[3,4]])
# pinv is pseudo inversion for stability
print(np.linalg.pinv(c))
print('-'*30)
# l2 norm by default, read documentation for more options
print(np.linalg.norm(c))
print('-'*30)
# summing a matrix
print(np.sum(c))
print('-'*30)
# the optional axis parameter
print(c)
print(np.sum(c, axis=0)) # sum along axis 0
print(np.sum(c, axis=1)) # sum along axis 1

[[-2.   1. ]
 [ 1.5 -0.5]]
------------------------------
5.477225575051661
------------------------------
10
------------------------------
[[1 2]
 [3 4]]
[4 6]
[3 7]


In [27]:
c = np.array([1,2])
d = np.array([3,4])
print(np.dot(c,d))

11


In [29]:
# matrix multiplication
a = np.ones((4,3)) # 4,3
b = np.ones((3,2)) # 3,2 --> 4,2
print(a @ b) # same as a.dot(b)
print('-'*30)
c = a @ b # (4,2)
# automatic repetition along axis
d = np.array([1,2,3,4]).reshape(4,1)
print(c + d)
print('-'*30)
# handy for batch operation
batch = np.ones((3,32))
weight = np.ones((32,10))
bias = np.ones((1,10))
print((batch @ weight + bias).shape)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]
------------------------------
[[4. 4.]
 [5. 5.]
 [6. 6.]
 [7. 7.]]
------------------------------
(3, 10)


In [34]:
a = np.ones((3,3))
# element-wise operations, for examples
print(np.log(a),'\n')
print(np.exp(a),'\n')
print(np.sin(a),'\n')
# operation with scalar is interpreted as element-wise
a * 3

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 

[[2.71828183 2.71828183 2.71828183]
 [2.71828183 2.71828183 2.71828183]
 [2.71828183 2.71828183 2.71828183]] 

[[0.84147098 0.84147098 0.84147098]
 [0.84147098 0.84147098 0.84147098]
 [0.84147098 0.84147098 0.84147098]] 



array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])